services:
  postgres:
    image: postgres:latest
    container_name: digital-wallet-users
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: digital-wallet
    ports:
      - "5430:5432"
    volumes:
      - my_postgres_data:/var/lib/postgresql/data

volumes:
  my_postgres_data: